### ISSUE TITLE
How to cross compile for OpenWRT (Atheros / MIPS)

### ISSUE THREAD

**Issue by captcha1** [timmathews/argo#2]
How to cross compile :

export GOARCH=mips

export GOMIPS=softfloat # need go-1.10 for softfloat code gen

I found a bug in go-serial (hard coded constants in
serial/open_linux.go need to be changed for OpenWRT) : I filed a bug
w/ go-serial.

**Comment by timmathews** [comment]
8a69dbb29eff955188eb3e79bf6920d76ef73cd4 adds instructions in README for cross platform builds.
